title: "NotionUS"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: " AY2223S1-CS2103T-F12-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
