title: "ArtBuddy"
remote_theme: just-the-docs/just-the-docs

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2223S1-CS2103T-W11-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
