title: "InterNUS"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2223S1-CS2103T-F11-1/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
