title: "Duke The Market"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2223S1-CS2103-F09-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
